# VM Agent Configuration
agent:
  id: ${VM_ID}  # Set via environment variable
  name: "VM Agent ${VM_ID}"
  version: "1.0.0"
  
server:
  host: "0.0.0.0"
  port: 8080
  max_connections: 100
  request_timeout: 30
  
security:
  api_key: ${API_KEY}  # Set via environment variable
  allowed_hosts: 
    - "*"  # Restrict in production
  rate_limit:
    requests_per_minute: 100
    
tools:
  shell_executor:
    enabled: true
    timeout_default: 30
    timeout_max: 300
    allowed_commands: "*"  # Restrict in production
    blocked_commands:
      - "rm -rf /"
      - "mkfs"
      - "dd if="
    
  file_manager:
    enabled: true
    max_file_size: 10485760  # 10MB
    allowed_paths:
      - "/var/log/*"
      - "/etc/*"
      - "/tmp/*"
    blocked_paths:
      - "/etc/shadow"
      - "/etc/passwd"
    
  system_monitor:
    enabled: true
    metrics_cache_ttl: 5  # seconds
    
  log_analyzer:
    enabled: true
    max_lines_default: 1000
    max_lines_max: 10000

logging:
  level: INFO
  file: "/var/log/vm-agent.log"
  max_size: 50MB
  backup_count: 3